### ISSUE TITLE
CPP not loading in correctly

### ISSUE THREAD

**Issue by gltchii** [KyleTheScientist/ComputerPlusPlus#3]
I like this mod, but when I try and use it in the current update, it only appears in the left eye, and doesn't function. What I mean is that I can navigate the menus, but there is no Background or anything, also it makes it a bit off center. Please fix!

**Comment by bubzilla** [comment]
Are you using computer interface? That mod is broken and this mod is not. Please close this issue as it seems to be for the wrong repository.
